CREATE DATABASE IF NOT EXISTS streamdb;
USE streamdb;


CREATE TABLE Rating (
    ratingID VARCHAR(10) PRIMARY KEY
);


CREATE TABLE Length (
    lengthID INT PRIMARY KEY,
    lengthCategory VARCHAR(50) NOT NULL
);


CREATE TABLE Genre (
    genreID INT PRIMARY KEY,
    genreName VARCHAR(50) NOT NULL
);


CREATE TABLE Film (
    filmID INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    releaseYear YEAR,
    filmDescription TEXT,
    genreID INT,
    lengthID INT,
    ratingID VARCHAR(10),
    FOREIGN KEY (genreID) REFERENCES Genre(genreID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (lengthID) REFERENCES Length(lengthID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ratingID) REFERENCES Rating(ratingID) ON DELETE SET NULL ON UPDATE CASCADE
);


CREATE TABLE Series (
    prequelID INT,
    sequelID INT,
    PRIMARY KEY (prequelID, sequelID),
    FOREIGN KEY (prequelID) REFERENCES Film(filmID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (sequelID) REFERENCES Film(filmID) ON DELETE CASCADE ON UPDATE CASCADE
);
