CREATE TABLE Genre (
    genreID INT NOT NULL,
    genreName VARCHAR(50) NOT NULL,
    CONSTRAINT GENREPK PRIMARY KEY (genreID)
);

CREATE TABLE Length (
    lengthID INT NOT NULL,
    lengthCategory VARCHAR(50),
    CONSTRAINT LENGTHPK PRIMARY KEY (lengthID)
);

CREATE TABLE Rating (
    ratingID VARCHAR(10) NOT NULL,
    ratingDescription VARCHAR(50),
    CONSTRAINT RATINGPK PRIMARY KEY (ratingID)
);

CREATE TABLE Film (
    filmID INT NOT NULL,
    title VARCHAR(100) NOT NULL,
    releaseYear INT,
    filmDescription VARCHAR(255),
    genreID INT,
    lengthID INT,
    ratingID VARCHAR(10),
    CONSTRAINT FILMPK PRIMARY KEY (filmID),
    CONSTRAINT FILMFK1 FOREIGN KEY (genreID) REFERENCES Genre(genreID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FILMFK2 FOREIGN KEY (lengthID) REFERENCES Length(lengthID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FILMFK3 FOREIGN KEY (ratingID) REFERENCES Rating(ratingID)
        ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Series (
    prequelID INT NOT NULL,
    sequelID INT NOT NULL,
    CONSTRAINT SERIESPK PRIMARY KEY (prequelID, sequelID),
    CONSTRAINT SERIESFK1 FOREIGN KEY (prequelID) REFERENCES Film(filmID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SERIESFK2 FOREIGN KEY (sequelID) REFERENCES Film(filmID)
        ON DELETE CASCADE ON UPDATE CASCADE
    --removed SERIESNODUPES because it's invalid in MySQL
);
